### PR TITLE
Crossover

### PR DESCRIPTION
**Pull request by samwalle**
Two crossover function added. The build on the idea of heuristic crossover function in wich there fitness score determine their representation of genes in the offsprings. The first function focuses on swithsing single genes based on rulett wheel and the later function change the crossover point in favour for the "stronger" parent.

### CODE REVIEW

**Review by JoelScarinius — CHANGES_REQUESTED** [review]
Seems as you have indentation issues, are you using tabs when indenting?

**Review by Linkan42 — APPROVED** [review]
chatgpt didn't find anything wrong with it so i trust it works

**Review by OskarSundberg — APPROVED** [review]

**Review by JoelScarinius — CHANGES_REQUESTED** [review]
Please from this branch run git merge origin main, if there are any conflicts fix them and push again. I also want to see all new workflows pass before approving.

**Review by JoelScarinius — APPROVED** [review]
Well done, LGTM!

**Pull request merged**
